### ISSUE TITLE
希望大佬提供个create account 的交易类型

### ISSUE THREAD

**Issue by mycodeku** [0x6368616e67/aptos-sdk-go#1]
首先感谢大佬的分享，解决了我很多的问题。不过今天我在进行研究时发现aptos地址都需要进行创建操作。详见https://aptos.dev/guides/interacting-with-the-aptos-blockchain#creating-a-new-account。现在我自己写的是个外挂的程序，很不美观。如果大佬能把这个功能加上将感激不尽。

**Comment by 0x6368616e67** [comment]
the doc is outdated. see https://github.com/aptos-labs/aptos-core/issues/5122

**Comment by mycodeku** [comment]
感谢大佬的解答，笔芯
